name: Deploy to the server

on:
  push:
    branches: [ master, dev ]

jobs:
  # master
  deploy_master:
    name: Depoy to the production server.
    if: ${{ contains(github.ref, 'master') }}
    runs-on: ubuntu-latest
    env:
      SERVER_GIT_ROOT: /home/tokupe/website-engine.com/public_html/wp-content
      BRANCH_NAME: master
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          script: |
          cd /home/tokupe/website-engine.com/public_html/wp-content
          git fetch
          git checkout master
          git pull origin master
          exit
  # staging
  deploy_staging:
    name: Depoy to the staging server.
    if: ${{ contains(github.ref, 'dev') }}
    runs-on: ubuntu-latest
    env:
      SERVER_GIT_ROOT: /home/tokupe/website-engine.com/public_html/test/wp-content
      BRANCH_NAME: dev
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          script: |
          cd /home/tokupe/website-engine.com/public_html/test/wp-content
          git fetch
          git checkout dev
          git pull origin dev
          exit
