name: Deploy to the server

on:
  push:
    branches: [ master, dev ]

jobs:
  # master
  deploy_master:
    name: Depoy to the production server.
    if: ${{ contains(github.ref, 'master') }}
    runs-on: ubuntu-latest
    env:
      SERVER_GIT_ROOT: /home/tokupe/website-engine.com/public_html/wp-content
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          script: |
          BRANCH=$(echo ${{ github.ref }} | sed -e 's/refs\/heads\///g')
          cd ${{ env.SERVER_GIT_ROOT }}
          git fetch
          git checkout $BRANCH
          git pull origin $BRANCH
          exit
  # staging
  deploy_staging:
    name: Depoy to the staging server.
    if: ${{ contains(github.ref, 'dev') }}
    runs-on: ubuntu-latest
    env:
      SERVER_GIT_ROOT: /home/tokupe/website-engine.com/public_html/test/wp-content
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          script: |
          BRANCH=$(echo ${{ github.ref }} | sed -e 's/refs\/heads\///g')
          cd ${{ env.SERVER_GIT_ROOT }}
          git fetch
          git checkout $BRANCH
          git pull origin $BRANCH
          exit
